version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - database.env
    ports:
      - 5435:5432
    expose:
      - 5435
    volumes: 
      - db:/var/lib/postgresql/data
  dbadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=dbt@jitsejan.com
      - PGADMIN_DEFAULT_PASSWORD=dbttest
    ports:
      - '82:80'
volumes:
  db:
    driver: local




